export type SimulatorZone = "Standard" | "VIP";
export type SimulatorType = SimulatorZone;
export type SimulatorStatus = "ready_to_play" | "busy" | "reserved" | "unpaid" | "broken" | "repair_requested" | "repair_approved" | "fixing" | "fixed_waiting_confirmation" | "offline" | "locked";
export type PaymentStatus = "paid" | "unpaid" | "partial";
export type RepairErrorType = "game_error" | "device_error" | "network_error" | "payment_error" | "hardware_error" | "other";
export type RepairPriority = "low" | "medium" | "high" | "critical";
export type RepairApprovalStatus = "pending" | "approved" | "rejected" | "more_details_requested" | "fixing" | "fixed_waiting_confirmation" | "confirmed_fixed";
export type MaintenanceReviewStatus = "open" | "pending_review" | "cleared" | "charged";
export type SimulatorMapPosition = {
  floor?: string;
  col: number;
  row: number;
  colSpan?: number;
  rowSpan?: number;
};

export type RepairRequest = {
  id: string;
  simulatorId: string;
  sessionId?: string;
  openedDuringSession?: boolean;
  simulatorName: string;
  branchId: string;
  branchName: string;
  requestedBy: string;
  requestedAt: string;
  title: string;
  description: string;
  errorType: RepairErrorType;
  priority: RepairPriority;
  note?: string;
  status: RepairApprovalStatus;
  affectedRevenue: number;
  approvedAt?: string;
  fixingStartedAt?: string;
  fixedAt?: string;
  confirmedAt?: string;
  rejectedAt?: string;
  resolutionNote?: string;
  // Maintenance accountability flow
  reviewStatus: MaintenanceReviewStatus;
  requestedByName?: string;
  reviewedByName?: string;
  openedAt?: string;
  closedAt?: string;
  durationMinutes?: number;
  chargeAmount: number;
};

export type Simulator = {
  id: string;
  name: string;
  type: SimulatorType;
  zone: SimulatorZone;
  branchId: string;
  branchName: string;
  status: SimulatorStatus;
  deviceId: string;
  ipAddress: string;
  currentUser?: string;
  phone?: string;
  tariff?: string;
  startedAt?: string;
  remainingMinutes: number;
  remainingSeconds?: number;
  billingMode?: "fixed" | "open";
  hourlyRate?: number;
  elapsedSeconds?: number;
  accruedAmount?: number;
  paidAmount: number;
  paymentStatus: PaymentStatus;
  orderItems: string[];
  repairRequestId?: string;
  rigId?: string;
  rigHostname?: string;
  rigVersion?: string;
  rigLatestVersion?: string;
  rigNeedsUpdate?: boolean;
  rigOnline?: boolean;
  rigUnlockUntil?: string | null;
  rigUpdateStatus?: string;
  rigLastSeen?: string | null;
  currentSessionId?: string | null;
  mapPosition?: SimulatorMapPosition;
};
