import { Router } from "express";
import { requireRole } from "../../middleware/role.middleware";
import * as c from "./simulators.controller";
export const simulatorsRoutes = Router();
simulatorsRoutes.get("/map", c.map);
simulatorsRoutes.get("/", c.list);
simulatorsRoutes.post("/push-update", requireRole(["super_admin"]), c.pushUpdate);
simulatorsRoutes.get("/:id", c.get);
simulatorsRoutes.patch("/:id/status", requireRole(["super_admin"]), c.patchStatus);
simulatorsRoutes.post("/:id/notify", requireRole(["super_admin"]), c.notify);
simulatorsRoutes.post("/:id/lock", requireRole(["super_admin"]), c.lock);
simulatorsRoutes.post("/:id/unlock", requireRole(["super_admin"]), c.unlock);
simulatorsRoutes.post("/:id/timed-unlock", requireRole(["super_admin"]), c.timedUnlock);
simulatorsRoutes.post("/:id/reboot", requireRole(["super_admin"]), c.reboot);
simulatorsRoutes.post("/:id/request-status", c.requestStatus);
